switch to theme
alex13bright/tower-site pull request #3
Opened 2022-06-08 14:12 UTC by alex13bright

Extract PageWrapper logic to separate component
Setup styled components theme

2022-06-08 14:35 UTC, alex-adamant requested changes
No really big blockers, just some minor requests and considerations.

2022-06-08 14:35 UTC, alex-adamant commented on app/components/StickyComponent.tsx
> +// import { ReactElement } from 'react'
Normally we should never commit commented code.

2022-06-08 14:35 UTC, alex-adamant commented on app/components/PageFooter.tsx
> +    ${(props) => props.theme.background.colors.main.start} 47.41%,
I never really worked with themes in StyledComponents. I wonder if it's the best practise for working with them? 

It looks OK, but still, too noisy, especially with all the nested props structure.
I guess it's ok for now, no need to sweat over it. Maybe later we'll come up with a better structure for it.

2022-06-08 14:41 UTC, alex-adamant commented on app/styles/styled.d.ts
> +    background: {
What if we do the whole structure a little bit flatter?
What other props are we gonna use in theme?
Mostly it's colors?

Why, by the way, do we have breakpoints here? Will they ever change? Will they be customised?

2022-06-08 14:43 UTC, alex-adamant commented on app/styles/styled.d.ts
> +    background: {
And since theming is mostly colors (it's not just like you're gonna make paddings customisable :)).
Usually in design systems we use just the names of the colors. Like `main`, `secondary`, `danger`, etc. So we can keep them on the very top level. And  don't make it different for background and text, btw. If the main website color is blue, it is blue in design system. And if main bg color is brown, it's already a secondary (or just background-color (1,2, etc) by definition.

2022-06-08 14:44 UTC, alex13bright commented on app/components/StickyComponent.tsx
> +// import { ReactElement } from 'react'
Я слашыл про коменты, стараюсь ничеге не оставлять. Тут я вообще не хотел этот файл комитить, но в итоге забыл про него)) Надо будет больше акцентироваться на этом в будущем.

2022-06-08 14:48 UTC, alex13bright commented on app/styles/StyledTheme.tsx
> +export const StyledComponentsTheme: (props: Props) => ReactElement = ({ children }) => {
Точно, я только сейчас понял о чем ты писал. Мне в твоем варианте даже удобнее, и читается приятнее.

2022-06-08 14:51 UTC, alex13bright commented on app/components/PageFooter.tsx
> +    ${(props) => props.theme.background.colors.main.start} 47.41%,
Я сегодня увидел в документации, решил попробовать. Может быть это и не нужно.
То что там такая вложеность это не вина именно самой техники, тут скорее я зря так сильно навкладывал.

2022-06-08 14:57 UTC, alex-adamant commented on app/styles/StyledTheme.tsx
> +  const [theme, setTheme] = useState<any>(defaultTheme)
You know, if it's boring/difficult to type now, it'll rarely be more fascinating/easy in future :) So I'd suggest to type it as thorough as possible.

Also, a difficult data structure/method to type often means some over-complicated logic.

2022-06-08 15:00 UTC, alex13bright commented on app/styles/styled.d.ts
> +    background: {
Насчет вложености согласен, написал выше, она портит читаемость.
Что касается breakpoints и подобные ей переменные тут надо подумать, я как то пропустил этот момент.
Возможно их не надо вместе с темой таскать. С одной стороны все стилистические настройки унифицированно в все в одном месте, что вроде как хорошо. С другой стороны возможно все в один файл складывать все равно будет неудобно. Придется все равно потом дробить по файлам и мерджить их в объект темы. 
Давай наверно я выделю их в отдельный файл.
Как плюс такого подхода не надо задумываться что будет переопределяться, а что нет. Я думаю будут примеры где уже не будет так очевидно. Хотя возможно это слабый агрумент))

2022-06-08 15:04 UTC, alex13bright commented on app/styles/StyledTheme.tsx
> +  const [theme, setTheme] = useState<any>(defaultTheme)
Не знаю как тут сделать ссылку на код. Сегодня я пытался типизировать as prop. Ответ был тут.
https://stackoverflow.com/questions/67970513/typescript-error-with-styled-components-and-as-ts2769-no-overload-matches-this
Очень говоряще ребята перекинулись фразами к ответу:
![image](https://user-images.githubusercontent.com/52797009/172650663-1b27a898-1384-4d3e-aed8-2bb2c9294208.png)

2022-06-08 15:09 UTC, alex-adamant commented on app/styles/StyledTheme.tsx
> +  const [theme, setTheme] = useState<any>(defaultTheme)
Okay, let's agree in such cases to add
```
// TODO: Type it properly. 
// You can add here a link to a discussion, for instance, that may hint about how to type it.
```

Sometimes you can do something like:
type A = Record<string, unknown> if it's an object.

2022-06-09 07:17 UTC, alex13bright commented on app/styles/StyledTheme.tsx
> +export const StyledComponentsTheme: (props: Props) => ReactElement = ({ children }) => {
While searching for incorrect versions in the project I found this one. Just to be totally sure that the props get the right type)))
![image](https://user-images.githubusercontent.com/52797009/172787293-60ee2833-df55-4ce8-a3f2-104f942e47a7.png)

2022-06-09 08:05 UTC, alex13bright commented on app/styles/StyledTheme.tsx
> +    <SetThemeContext.Provider value={{ setTheme }}>
A good point! I will think about it in the future any time I will use a context provider. At least I think I should consider a) how many components will "suffer" from rerender and b) will the context propvider be actually rerendered so often.

It is theme so there must be a lot of comnponents who depend on the theme. But the answer to b) is not so obvious to me. In theory root must not be re-render often if ever.

But on the other hand React memoization with useMemo is so neat and easy to use. So I'm gonna wrap theme in it any way.

2022-06-09 12:55 UTC, alex-adamant commented on app/styles/StyledTheme.tsx
> +    <SetThemeContext.Provider value={{ setTheme }}>
Yeah, you can't really do it. And it's quite dangerous to turn this flag off. You're trying to hijack the memoizing logic here. Instead of it you can just make sure theme don't get updated too often.

But my comment was about `{{ setTheme }}` and not the `theme`. Passing it like this and not like `value={setTheme}` will recreate the context value on every render.

2022-06-09 12:59 UTC, alex-adamant commented on app/components/PageFooter.tsx
> +import { pageMainBlock } from '~/styles/commonStyles'
Where do we set this `~` path? It's not just the system-wide `~` (like 'Home directory'), is it?

2022-06-09 13:01 UTC, alex-adamant commented on app/components/StyledComponentsTheme.tsx
> +  const memoizedTheme = useMemo(() => theme, [theme.id])
Sorry, I must have expressed myself inaccurately. You don't need to memoize `theme` here. We _do_ want to update the values on every `theme` change (of any type). What I was referring to is the `{{ setTheme }}` inline object that gets re-created every time here even though `setTheme` callback **never** gets updated by definition.

2022-06-09 13:06 UTC, alex-adamant commented on app/styles/styleConfig.ts.tsx
> +export const breakpoints = {
We can add another layer here, importing also something like:

```
export const screenAtLeast = {
  mobile: `(min-width: ${breakpoints.mobile}px)`,
  tablet: `(min-width: ${breakpoints.tablet}px)`,
  laptop: `(min-width: ${breakpoints.laptop}px)`,
  desktop: `(min-width: ${breakpoints.desktop}px)`,
};
```

So that somewhere in the code you could write:
```
  @media ${screenAtLeast.lg} {
    pointer-events: none;
    margin-left: 4px;
  }
```
And don't repeat parenthesis and `min-width` part every time.
Obviously, if needed, you can also add `screenAtMost` set of constants.

2022-06-09 13:20 UTC, alex13bright commented on app/components/PageFooter.tsx
> +import { pageMainBlock } from '~/styles/commonStyles'
This is typescript configuration staff. As far as I know remix does not use ts for building it is reading config file and know how to resolve such pathes though.

2022-06-10 07:09 UTC, alex13bright commented on app/styles/styleConfig.ts.tsx
> +export const breakpoints = {
I like it. Looks very tidy!

2022-06-11 14:55 UTC, alex-adamant commented on app/components/DevCom.tsx
> +// import { ReactElement, useRef } from 'react'
I still don't understand why do you need to comment out this code? Why don't you just leave it as it is? Even if it's unused, it won't affect anything.

2022-06-11 14:55 UTC, alex-adamant commented on app/components/Sticky.tsx
> +export const useStickContext = () => {
I love this hook!

2022-06-11 14:55 UTC, alex-adamant commented on app/custom-hooks/useIsVisible.ts
> +export const useIsVisible = (ref: MutableRefObject<HTMLDivElement | null>): boolean => {
Nice one!

2022-06-11 14:55 UTC, alex-adamant commented on app/components/Sticky.tsx
> +  isFooterVisible: boolean
I wonder if we will ever need to track these two separately. Currently we split it here only to combine it back together later in `StickyWrapper`. What if we use just one boolean like `shouldShowStickyBox` or something and two wrappers both just update this flag?

2022-06-11 14:55 UTC, alex-adamant commented on app/components/Sticky.tsx
> +  display: ${({ isVisible }) => (isVisible ? 'grid' : 'none')};
Just note to the future: we'll have to add an animation here, so it'll be a bit more complicated than `none-grid` change.

2022-06-11 15:21 UTC, alex13bright commented on app/custom-hooks/useIsVisible.ts
> +export const useIsVisible = (ref: MutableRefObject<HTMLDivElement | null>): boolean => {
Ты подсказал очень крутой api. Старанной что я вообще не слышал про него раньше. Многие вещи на нем делаются проще, но главное что он вообще не загружает сайт. Раньше надо было обрабатывать каждое минимальное движение скрола, колбэк вызывался милионы раз, а сейчас он вызывается только тогда когда надо. Плюс там еще есть параметр threshold, он позволяет еще сильнее сузить количество вызовов.

2022-06-11 15:35 UTC, alex13bright commented on app/components/Sticky.tsx
> +  isFooterVisible: boolean
Надо подумать, а но наскидку у меня такое ощущение что тут сжатие с потерей информации) Вроде как нельзя вывести значение флага если видеть только половину картины.

2022-06-11 15:38 UTC, alex13bright commented on app/components/DevCom.tsx
> +// import { ReactElement, useRef } from 'react'
У меня не работающий код вызывает меньшее раздражение чем закомментированный. Видимо у тебя наоборот. Буду вне проекта такое хранить тогда пока. Кстати большую часть такого кода я уже раскомментировал.

2022-06-12 05:12 UTC, merged